<?php
/**
 * LinMeng Blog one-time installer.
 * It creates a local .env file, initializes the empty MySQL database, and creates the first administrator.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$markerFile = $root . '/includes/config_installed.php';
$envFile = $root . '/.env';
$schemaFile = __DIR__ . '/schema.sql';

function setupEscape($value): string {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function setupInstalled(string $markerFile): bool {
    if (!is_file($markerFile)) {
        return false;
    }
    $installed = include $markerFile;
    return $installed === true;
}

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}
if (empty($_SESSION['setup_csrf'])) {
    $_SESSION['setup_csrf'] = bin2hex(random_bytes(24));
}

$values = [
    'site_name' => '',
    'site_description' => '',
    'site_url' => '',
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_name' => '',
    'db_user' => '',
    'admin_username' => '',
    'admin_email' => '',
    'admin_nickname' => '',
];
$errors = [];
$success = false;
$alreadyInstalled = setupInstalled($markerFile);
$requestMethod = $_SERVER['REQUEST_METHOD'] ?? 'GET';

if (!$alreadyInstalled && $requestMethod === 'POST') {
    foreach ($values as $key => $default) {
        $values[$key] = trim((string)($_POST[$key] ?? $default));
    }
    $dbPassword = (string)($_POST['db_password'] ?? '');
    $adminPassword = (string)($_POST['admin_password'] ?? '');
    $adminPasswordConfirm = (string)($_POST['admin_password_confirm'] ?? '');
    $csrf = (string)($_POST['setup_csrf'] ?? '');

    if (!hash_equals($_SESSION['setup_csrf'], $csrf)) {
        $errors[] = '页面已过期，请刷新后重试。';
    }
    if ($values['site_name'] === '' || strlen($values['site_name']) > 120) {
        $errors[] = '请填写 1–120 个字符的网站标题。';
    }
    if ($values['site_url'] === '' || !filter_var($values['site_url'], FILTER_VALIDATE_URL)
        || !in_array(strtolower((string)parse_url($values['site_url'], PHP_URL_SCHEME)), ['http', 'https'], true)) {
        $errors[] = '请填写有效的网站地址（以 http:// 或 https:// 开头）。';
    }
    if (!preg_match('/^[A-Za-z0-9.:-]{1,253}$/', $values['db_host'])) {
        $errors[] = '数据库主机格式不正确。';
    }
    if (!ctype_digit($values['db_port']) || (int)$values['db_port'] < 1 || (int)$values['db_port'] > 65535) {
        $errors[] = '数据库端口必须在 1–65535 之间。';
    }
    if (!preg_match('/^[A-Za-z0-9_]{1,64}$/', $values['db_name'])) {
        $errors[] = '数据库名只能使用字母、数字和下划线。';
    }
    if (!preg_match('/^[A-Za-z0-9_@.$-]{1,128}$/', $values['db_user'])) {
        $errors[] = '数据库用户名格式不正确。';
    }
    if (!preg_match('/^[A-Za-z0-9_-]{3,32}$/', $values['admin_username'])) {
        $errors[] = '管理员用户名应为 3–32 位字母、数字、下划线或短横线。';
    }
    if (!filter_var($values['admin_email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = '请填写有效的管理员邮箱。';
    }
    if (strlen($values['admin_nickname']) > 100) {
        $errors[] = '管理员显示名称不能超过 100 个字符。';
    }
    if (preg_match('/[\r\n]/', $dbPassword)) {
        $errors[] = '数据库密码不能包含换行符。';
    }
    if (strlen($adminPassword) < 8) {
        $errors[] = '管理员密码至少需要 8 个字符。';
    } elseif ($adminPassword !== $adminPasswordConfirm) {
        $errors[] = '两次输入的管理员密码不一致。';
    }
    if (is_file($envFile)) {
        $errors[] = '检测到现有 .env 配置。为避免覆盖已有部署，安装向导已停止。';
    }
    if (!is_writable($root) || !is_writable(dirname($markerFile))) {
        $errors[] = '项目根目录或 includes 目录不可写，无法保存安装配置。';
    }
    if (!is_readable($schemaFile)) {
        $errors[] = '找不到数据库结构文件。';
    }

    if (!$errors) {
        $envCreated = false;
        $markerCreated = false;
        try {
            $siteUrl = rtrim($values['site_url'], '/');
            $secret = bin2hex(random_bytes(32));
            $env = "# Generated by /setup/ on " . gmdate('c') . "\n"
                . "DB_HOST=\"{$values['db_host']}\"\n"
                . "DB_PORT=\"{$values['db_port']}\"\n"
                . "DB_NAME=\"{$values['db_name']}\"\n"
                . "DB_USER=\"{$values['db_user']}\"\n"
                . "DB_PASS=\"{$dbPassword}\"\n"
                . "SECRET_KEY=\"{$secret}\"\n"
                . "SITE_URL=\"{$siteUrl}\"\n"
                . "SITE_PATH=\"\"\n"
                . "LM_TRUST_PROXY=false\n";
            $pendingEnv = $envFile . '.pending-' . bin2hex(random_bytes(6));
            if (file_put_contents($pendingEnv, $env, LOCK_EX) === false || !@rename($pendingEnv, $envFile)) {
                @unlink($pendingEnv);
                throw new RuntimeException('无法写入本地配置文件。');
            }
            $envCreated = true;

            $pdoOptions = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            $dsn = 'mysql:host=' . $values['db_host'] . ';port=' . (int)$values['db_port'] . ';charset=utf8mb4';
            $pdo = new PDO($dsn, $values['db_user'], $dbPassword, $pdoOptions);
            $database = '`' . $values['db_name'] . '`';
            try {
                $pdo->exec('CREATE DATABASE IF NOT EXISTS ' . $database . ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            } catch (PDOException $exception) {
                // Many shared-hosting accounts can use an existing database but cannot create one.
            }
            $pdo->exec('USE ' . $database);

            $hasAdminTable = $pdo->query("SHOW TABLES LIKE 'lm_admin'")->fetchColumn();
            if ($hasAdminTable && (int)$pdo->query('SELECT COUNT(*) FROM lm_admin')->fetchColumn() > 0) {
                throw new RuntimeException('目标数据库已包含管理员账号。');
            }

            $schema = (string)file_get_contents($schemaFile);
            $schema = preg_replace('/^\s*--.*(?:\r?\n|$)/m', '', $schema);
            foreach (preg_split('/;\s*(?:\r?\n|$)/', $schema) ?: [] as $statement) {
                $statement = trim($statement);
                if ($statement !== '') {
                    $pdo->exec($statement);
                }
            }

            $pdo->beginTransaction();
            $insertSetting = $pdo->prepare(
                'INSERT INTO lm_setting (setting_key, setting_value) VALUES (?, ?) '
                . 'ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)'
            );
            $settings = [
                'site_name' => $values['site_name'],
                'site_description' => $values['site_description'],
                'site_keywords' => '',
                'site_footer' => '',
                'admin_email' => $values['admin_email'],
                'site_start_date' => date('Y-m-d H:i:s'),
                'site_theme' => 'auto',
                'comment_need_approve' => '0',
                'article_comment_enable' => '1',
                'guestbook_enable' => '1',
            ];
            foreach ($settings as $key => $value) {
                $insertSetting->execute([$key, $value]);
            }
            $nickname = $values['admin_nickname'] !== '' ? $values['admin_nickname'] : $values['admin_username'];
            $insertAdmin = $pdo->prepare(
                "INSERT INTO lm_admin (username, password, email, nickname, role, status) VALUES (?, ?, ?, ?, 'admin', 1)"
            );
            $insertAdmin->execute([
                $values['admin_username'],
                password_hash($adminPassword, PASSWORD_DEFAULT),
                $values['admin_email'],
                $nickname,
            ]);

            if (file_put_contents($markerFile, "<?php\nreturn true;\n", LOCK_EX) === false) {
                throw new RuntimeException('无法写入安装锁定文件。');
            }
            $markerCreated = true;
            $pdo->commit();
            unset($_SESSION['setup_csrf']);
            $success = true;
        } catch (Throwable $exception) {
            if (isset($pdo) && $pdo->inTransaction()) {
                $pdo->rollBack();
            }
            if ($envCreated && is_file($envFile)) {
                @unlink($envFile);
            }
            if ($markerCreated) {
                @file_put_contents($markerFile, "<?php\nreturn false;\n", LOCK_EX);
            }
            error_log('Setup failed: ' . $exception->getMessage());
            $errors[] = '初始化失败：请确认数据库主机、账号权限和 PHP 的 pdo_mysql 扩展可用，然后重试。';
        }
    }
}
?>
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title>安装 LinMeng Blog</title>
    <style>
        :root { color-scheme: light dark; font-family: Inter, "Microsoft YaHei", system-ui, sans-serif; }
        * { box-sizing: border-box; }
        body { margin: 0; min-height: 100vh; color: #252131; background: radial-gradient(circle at top left, #ebe8ff, transparent 36%), #f7f7fb; }
        main { width: min(760px, calc(100% - 32px)); margin: 42px auto; padding: 32px; border: 1px solid #e3e0ef; border-radius: 20px; background: rgba(255,255,255,.9); box-shadow: 0 20px 50px rgba(47, 39, 88, .12); }
        h1 { margin: 0; font-size: 28px; } p { line-height: 1.7; } .muted { color: #6a6579; } .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } .full { grid-column: 1 / -1; }
        label { display: grid; gap: 7px; color: #413a51; font-size: 14px; font-weight: 600; } input { width: 100%; min-height: 42px; padding: 10px 12px; border: 1px solid #cfc9dd; border-radius: 9px; background: #fff; color: #252131; font: inherit; }
        input:focus { outline: 3px solid rgba(105, 86, 213, .22); border-color: #6b58d5; } fieldset { margin: 24px 0; padding: 20px; border: 1px solid #e3e0ef; border-radius: 14px; } legend { padding: 0 8px; font-weight: 700; }
        button, .button { display: inline-block; padding: 11px 16px; border: 0; border-radius: 9px; color: #fff; background: #6956d5; font: inherit; font-weight: 700; text-decoration: none; cursor: pointer; } button:hover, .button:hover { background: #5844c4; }
        .alert { margin: 20px 0; padding: 14px 16px; border-radius: 10px; line-height: 1.6; } .error { color: #8e2525; background: #ffeded; } .success { color: #225f3b; background: #e9f9ef; } .notice { padding: 14px 16px; border-radius: 10px; background: #f4f2ff; color: #4f4388; }
        ul { margin: 0; padding-left: 20px; } a { color: #5140bc; } code { padding: 1px 5px; border-radius: 4px; background: #efedf7; } @media (max-width: 600px) { main { margin: 16px auto; padding: 22px; } .grid { grid-template-columns: 1fr; } .full { grid-column: auto; } }
        @media (prefers-color-scheme: dark) { body { color: #eae7f2; background: radial-gradient(circle at top left, #2e2852, transparent 36%), #14121c; } main { border-color: #3a3450; background: rgba(31,28,43,.92); } .muted { color: #b9b2c8; } label { color: #e1dcec; } input { border-color: #4d4661; background: #211e2e; color: #f4f1fa; } .notice { background: #302a50; color: #ded8ff; } .error { background: #532c34; color: #ffdbdf; } .success { background: #1f4934; color: #d5f7e2; } code { background: #312c43; } a { color: #c0b4ff; } }
    </style>
</head>
<body>
<main>
    <h1>LinMeng Blog 安装向导</h1>
    <p class="muted">配置数据库、站点标题与首个管理员账号。安装完成后会在服务器本地生成 <code>.env</code>，其中的配置不会写入仓库。</p>

    <?php if ($alreadyInstalled): ?>
        <div class="notice"><strong>该站点已安装。</strong> 为保护现有数据，安装向导已锁定。</div>
        <p><a class="button" href="/login.php">前往登录</a></p>
    <?php elseif ($success): ?>
        <div class="success"><strong>安装完成。</strong> 请妥善保管管理员账号；安装向导已自动锁定。</div>
        <p><a class="button" href="/login.php">前往管理员登录</a></p>
    <?php else: ?>
        <?php if ($errors): ?>
            <div class="alert error"><strong>请处理以下问题：</strong><ul><?php foreach ($errors as $error): ?><li><?php echo setupEscape($error); ?></li><?php endforeach; ?></ul></div>
        <?php endif; ?>
        <form method="post" autocomplete="off">
            <input type="hidden" name="setup_csrf" value="<?php echo setupEscape($_SESSION['setup_csrf']); ?>">
            <fieldset>
                <legend>站点信息</legend>
                <div class="grid">
                    <label>网站标题<input name="site_name" maxlength="120" required value="<?php echo setupEscape($values['site_name']); ?>" placeholder="我的博客"></label>
                    <label>网站描述<input name="site_description" maxlength="255" value="<?php echo setupEscape($values['site_description']); ?>" placeholder="记录与分享"></label>
                    <label class="full">网站地址<input type="url" name="site_url" required value="<?php echo setupEscape($values['site_url']); ?>" placeholder="https://example.com"></label>
                </div>
            </fieldset>
            <fieldset>
                <legend>MySQL 数据库</legend>
                <div class="grid">
                    <label>主机<input name="db_host" required value="<?php echo setupEscape($values['db_host']); ?>"></label>
                    <label>端口<input inputmode="numeric" name="db_port" required value="<?php echo setupEscape($values['db_port']); ?>"></label>
                    <label>数据库名<input name="db_name" required value="<?php echo setupEscape($values['db_name']); ?>"></label>
                    <label>数据库用户<input name="db_user" required value="<?php echo setupEscape($values['db_user']); ?>"></label>
                    <label class="full">数据库密码<input type="password" name="db_password" autocomplete="new-password"></label>
                </div>
            </fieldset>
            <fieldset>
                <legend>管理员账号</legend>
                <div class="grid">
                    <label>用户名<input name="admin_username" minlength="3" maxlength="32" required value="<?php echo setupEscape($values['admin_username']); ?>"></label>
                    <label>邮箱<input type="email" name="admin_email" required value="<?php echo setupEscape($values['admin_email']); ?>"></label>
                    <label class="full">显示名称（可选）<input name="admin_nickname" maxlength="100" value="<?php echo setupEscape($values['admin_nickname']); ?>"></label>
                    <label>密码<input type="password" name="admin_password" minlength="8" required autocomplete="new-password"></label>
                    <label>确认密码<input type="password" name="admin_password_confirm" minlength="8" required autocomplete="new-password"></label>
                </div>
            </fieldset>
            <button type="submit">初始化并完成安装</button>
        </form>
    <?php endif; ?>

    <p class="muted">部署推荐：<a href="https://www.rainyun.com/linmeng_" target="_blank" rel="noopener noreferrer">雨云</a>，优惠码 <code>linmeng</code> 可领取 5 折优惠券。</p>
</main>
</body>
</html>
